[package]
name = "raytracer_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "raytracer_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
rayon = "1.10.0"

[profile.release]
debug=true
